### PR TITLE
docs(intro): make some changes for egg-and-koa

### PR DESCRIPTION
**Pull request by SunShinewyf**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change
修改了一些文档中语法明显错误的地方

### CODE REVIEW

**Comment by atian25** [comment]
这个等 https://github.com/eggjs/egg/pull/1713 合并后再重新改改，那边有修改了对应的文件

**Comment by SunShinewyf** [comment]
好的

**Comment by dead-horse** [comment]
可以 rebase 了

**Comment by atian25** [comment]
@SunShinewyf 可以重新在新的基础上改了.

**Pull request merged**
