### PR TITLE
feat: move app.Service egg-core

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
依赖 https://github.com/eggjs/egg-core/pull/42

**Comment by fengmk2** [comment]
@popomore ci 过了就合并吧

**Comment by popomore** [comment]
@fengmk2 好的

**Comment by popomore** [comment]
travis 过了，我合了

**Pull request merged**
