### PR TITLE
Release 2.6.1

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

fix d.ts

### CODE REVIEW

**Comment by dead-horse** [comment]
rebase 一下吧

**Comment by atian25** [comment]
done

**Comment by waitingsong** [comment]
能把 https://github.com/eggjs/egg/pull/2359
这个合并了发布么

**Comment by atian25** [comment]
又忘记改 pkg 了。。。

**Comment by popomore** [comment]
没发版本？

**Pull request merged**
