### PR TITLE
docs: set the default locale zh-cn

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

doc

### CODE REVIEW

**Comment by popomore** [comment]
只是把 zh-cn/index.html 改成了首页，其他页面还是带 lang 的，省的拷贝了。

**Comment by popomore** [comment]
```
#0 [200] request http://localhost:8000/
#1 [200] request http://localhost:8000/zh-cn/
#2 [200] request http://localhost:8000/zh-cn/intro/
#3 [200] request http://localhost:8000/release/
#4 [200] request http://localhost:8000/zh-cn/advanced/loader.html
#5 [200] request http://localhost:8000/zh-cn/advanced/plugin.html
#6 [200] request http://localhost:8000/zh-cn/basics/env.html
#7 [200] request http://localhost:8000/zh-cn/basics/config.html
#8 [200] request http://localhost:8000/zh-cn/intro/index.html
#9 [200] request http://localhost:8000/zh-cn/advanced/framework.html
#10 [200] request http://localhost:8000/zh-cn/advanced/deployment.html
#11 [200] request http://localhost:8000/zh-cn/intro/egg-and-koa.html
#12 [200] request http://localhost:8000/zh-cn/basics/extend.html
#13 [200] request http://localhost:8000/zh-cn/intro/quickstart.html
#14 [200] request http://localhost:8000/zh-cn/basics/controller.html
#15 [200] request http://localhost:8000/zh-cn/basics/router.html
#16 [200] request http://localhost:8000/zh-cn/basics/middleware.html
#17 [200] request http://localhost:8000/zh-cn/basics/service.html
#18 [200] request http://localhost:8000/zh-cn/core/unittest.html
#19 [200] request http://localhost:8000/zh-cn/core/development.html
#20 [200] request http://localhost:8000/zh-cn/core/logger.html
#21 [200] request http://localhost:8000/zh-cn/basics/schedule.html
#22 [200] request http://localhost:8000/zh-cn/basics/app-start.html
#23 [200] request http://localhost:8000/zh-cn/core/security.html
#24 [200] request http://localhost:8000/zh-cn/core/httpclient.html
#25 [200] request http://localhost:8000/zh-cn/core/error-handling.html
#26 [200] request http://localhost:8000/zh-cn/core/i18n.html
#27 [200] request http://localhost:8000/zh-cn/core/view.html
#28 [200] request http://localhost:8000/zh-cn/advanced/view-plugin.html
#29 [200] request http://localhost:8000/zh-cn/tutorials/mysql.html
#30 [200] request http://localhost:8000/zh-cn/tutorials/restful.html
#31 [200] request http://localhost:8000/zh-cn/advanced/cluster.html
#32 [200] request http://localhost:8000/zh-cn/contributing.html
```

**Comment by atian25** [comment]
为何不是 zh_CN？

**Comment by fengmk2** [comment]
@popomore 发布一个到eg g j s.org吧

**Pull request merged**
