### PR TITLE
feat: move clusterPort to egg-cluster

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change

Ref https://github.com/eggjs/egg-cluster/pull/12

### CODE REVIEW

**Comment by popomore** [comment]
win 环境又挂了

**Comment by fengmk2** [comment]
重跑应该就好了

**Comment by popomore** [comment]
win 的又挂了

**Comment by popomore** [comment]
好了，需要 approve

**Pull request merged**
