### PR TITLE
Release 2.12.0

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
顺便把 egg-logger 的定义改了？

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-logger/blob/master/index.d.ts egg-logger 有定义，不知道和 egg 的有没有差别

**Comment by popomore** [comment]
https://github.com/eggjs/egg/pull/3078

**Comment by dead-horse** [comment]
rebased

**Pull request merged**
