### PR TITLE
perf: improve set type performance by lru cache

### PR DESCRIPTION
**Pull request by fengmk2**
only detect mimeType once on the same type

https://github.com/eggjs/egg/issues/2695

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
## before

image

## after

image

**Comment by fengmk2** [comment]
clinic 太方便了。

**Comment by dead-horse** [comment]
可以 pick 到 1.x

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg/blob/1.x/app/extend/response.js#L33 确实一样

**Pull request merged**
