### PR TITLE
chore: remove --fix for error check but not fix

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

package.json

##### Description of change

remove eslint --fix

### CODE REVIEW

**Comment by popomore** [comment]
Windows 还是无法删除目录的问题

**Comment by dead-horse** [comment]
+1

**Comment by fengmk2** [comment]
+1

**Comment by atian25** [comment]
其他库, 还有 boilerplate 要改么?

**Pull request merged**
