### PR TITLE
docs: fixed spelling mistake

### PR DESCRIPTION
**Pull request by yekexuan**
yeild ==> yield

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by jtyjty99999** [comment]
+1

**Comment by atian25** [comment]
PR 的分支一般是 `rebase master`, 而不是 `merge`.
PR 的分支是允许 `push -f` 的

**Comment by yekexuan** [comment]
@atian25 soga。。+1代表什么呢

**Comment by atian25** [comment]
不用 close ...  直接 rebase 修改 commit 后, `git push -f` 即可.

`+1 === LGTM === look good to me === could be merge`

**Pull request closed without merging**
