### PR TITLE
feat: remove egg logger local config

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- https://github.com/eggjs/egg-development/pull/7
- close https://github.com/eggjs/egg/issues/677

### CODE REVIEW

**Comment by atian25** [comment]
不移了，直接删掉。

cc @dead-horse @popomore

**Comment by atian25** [comment]
嗯，你接手修下用例？

**Comment by fengmk2** [comment]
@atian25 should make test pass before merge.

**Comment by popomore** [comment]
过了

**Comment by popomore** [comment]
@atian25 这个我直接合了

**Pull request merged**
