### PR TITLE
docs(core/cookie-and-session): translate section Cookie

### PR DESCRIPTION
**Pull request by zhang-z**
##### Checklist

- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

Work In Progress: Translate core/cookie-and-session

### CODE REVIEW

**Comment by popomore** [comment]
Thx for the translation. If you complete the translation, you can ping me to remove the label.

**Comment by zhang-z** [comment]
@popomore , the translation of cookie-and-session is done.

**Comment by zhang-z** [comment]
@dead-horse , updated according to your comment.

**Comment by dead-horse** [comment]
LGTM

**Pull request merged**
