### PR TITLE
feat: remove tracer

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

ctx.tracer

##### Description of change

remove ctx.tracer

### CODE REVIEW

**Comment by fengmk2** [comment]
logger 那个也改掉吧

**Comment by popomore** [comment]
logger 那个改掉，估计挺多用例要挂的

**Comment by popomore** [comment]
我先发个版本

**Comment by popomore** [comment]
+ egg@0.10.0

**Pull request merged**
