### PR TITLE
chore: fix 1.10.1 history.md

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by dead-horse** [comment]
发布了才想起来 egg 的发布规则不一样， 😢

**Comment by atian25** [comment]
把 master 配置为不能单独提交?

**Comment by popomore** [comment]
有限制，不过 @dead-horse 是例外

**Comment by atian25** [comment]
例外的是不是要罚钱?

**Comment by dead-horse** [comment]
> 例外的是不是要罚红包?

认罚

**Pull request merged**
