### PR TITLE
fix: improve ts definition for egg-static

### PR DESCRIPTION
**Pull request by njugray**
##### Checklist

- [ ] `npm test` passes
- [ ] commit message follows commit guidelines

##### Description of change

Support array usage of egg-static: 

> multiple directory by use dir: `[dir1, dir2, ...]` or dir: `[dir1, { prefix: '/static2', dir: dir2 }]`, static server will use all these directories.

### CODE REVIEW

**Comment by atian25** [comment]
prefer to move typings to egg-static 's own d.ts, then import it here

**Comment by njugray** [comment]
That would be much better if plugins maintain `d.ts` files themselves.

import plugins like we already done: 
```ts
import 'egg-onerror';
import 'egg-session';
...
```

plugin extend module egg:

```ts
import * as Egg from 'egg';

declare module 'egg' {
  // extend something, e.g. static config
  export interface EggAppConfig {
    static: {
      prefix: string;
      dir: string | Array<string | { prefix: string, dir: string}>;
      // support lazy load
      dynamic: boolean;
      preload: boolean;
      buffer: boolean;
      maxFiles: number;
    } & PlainObject;
  }
}

export = Egg;
```

**Comment by atian25** [comment]
@njugray yes, that is what I means

so plz raise PR to egg-static

**Comment by atian25** [comment]
will close this PR, and wait for another PR at egg-static.

thanks for your works

**Pull request closed without merging**
