### PR TITLE
Release 1.5.0

### PR DESCRIPTION
**Pull request by fengmk2**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
等 egg-bin 重新跑试试

**Comment by popomore** [comment]
跑完发布

**Comment by shepherdwind** [comment]
嗯，这个版本发了我改下 examples 里 ts 案例吧。watch 一下

**Comment by fengmk2** [comment]
1.5.0

**Pull request merged**
