### PR TITLE
Update middleware.md

### PR DESCRIPTION
**Pull request by x22x22**
middlewares是不是应该改成middleware?

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by atian25** [comment]
两个都可以的，印象中早期 app.middleware 是被 Koa 占用了的，后面好像搞定了。cc @popomore

**Comment by x22x22** [comment]
@atian25 
TypeError: app.middlewares is not a function

**Comment by x22x22** [comment]
那能在文档里说明一下吗?
因为用了typescript, 定义文件里没对middlewares属性进行描述, 这样乍一看还以为文档有问题.

**Comment by popomore** [comment]
搞定了，可以用 middleware 了

**Comment by atian25** [comment]
@x22x22 提个 PR 吧，改为 `app.middleware` 吧，英文版也要改

**Comment by x22x22** [comment]
https://github.com/eggjs/egg/pull/2077

**Pull request closed without merging**
