### PR TITLE
Release 1.13.1

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
等 x-forwarded-host 改了再发？

**Comment by fengmk2** [comment]
@popomore 对哦，一起发。

**Comment by popomore** [comment]
https://github.com/eggjs/egg/pull/2162

**Comment by fengmk2** [comment]
rebase

**Comment by dead-horse** [comment]
rebase 了

**Comment by fengmk2** [comment]
+1

@dead-horse 你来合并发布。

**Pull request merged**
