### PR TITLE
fix: AppWorkerClient subscribe same data failed issue

### PR DESCRIPTION
**Pull request by gxcsoccer**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

pick patch from internal version

### CODE REVIEW

**Comment by atian25** [comment]
```
2016-09-19 07:02:59,487 ERROR 2776 [chair-logger:buffer_write_stream] Error: EPERM: operation not permitted, open 'C:\projects\egg\test\fixtures\apps\demo\logs\demo\common-error.log'
Error: EPERM: operation not permitted, open 'C:\projects\egg\test\fixtures\apps\demo\logs\demo\common-error.log'
    at Error (native)
2016-09-19 07:02:59,487 ERROR 2776 [chair-logger:buffer_write_stream] Error: EPERM: operation not permitted, open 'C:\projects\egg\test\fixtures\apps\demo\logs\demo\demo-web.log'
Error: EPERM: operation not permitted, open 'C:\projects\egg\test\fixtures\apps\demo\logs\demo\demo-web.log'
    at Error (native)
2016-09-19 07:02:59,487 ERR
```

```
10) test/app/extend/context.test.js ctx.instrument(event, action), app.instrument(event, action) "before all" hook:
     Error: ENOTEMPTY: directory not empty, rmdir 'C:\projects\egg\test\fixtures\apps\context-config-app\logs\context-config-app'
      at Error (native)
      at Object.fs.rmdirSync (fs.js:758:18)
      at rmkidsSync (C:\projects\egg\node_modules\.2.5.4@rimraf\rimraf.js:342:11)
      at rmdirSync (C:\projects\egg\node_modules\.2.5.4@rimraf\rimraf.js:332:7)
      at rimrafSync (C:\projects\egg\node_modules\.2.5.4@rimraf\rimraf.js:303:9)
      at C:\projects\egg\node_modules\.2.5.4@rimraf\rimraf.js:340:5
      at Array.forEach (native)
      at rmkidsSync (C:\projects\egg\node_modules\.2.5.4@rimraf\rimraf.js:339:26)
```

**Comment by atian25** [comment]
不知道这个参数有没有用
```
Windows: EBUSY and ENOTEMPTY - rimraf will back off a maximum of opts.maxBusyTries times before giving up, adding 100ms of wait between each attempt. The default maxBusyTries is 3.
```

**Comment by gxcsoccer** [comment]
window 下 fs sync 的 API 都有问题

**Comment by fengmk2** [comment]
+1

**Pull request merged**
