### PR TITLE
docs: add year to licence && mysql docs

### LINKED ISSUE #416: Generate LICENSE automatically
Add a config to egg-ci, generating when every installation. And LICENSE should contain date.

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

close #416

### CODE REVIEW

**Comment by dead-horse** [comment]
没有改 licence 相关的？

**Comment by atian25** [comment]
对 https://choosealicense.com/licenses/mit/ 这个做个 diff, 貌似就是少了 YEAR

**Comment by dead-horse** [comment]
commit message 改一下吧

**Comment by atian25** [comment]
@dead-horse 改了 PR title, square 的话, commit message 就被抹掉了吧

**Comment by popomore** [comment]
恩？licence 那个文件没改？

**Comment by atian25** [comment]
额... 忘记 push 了

**Comment by atian25** [comment]
push 了, 再看看

**Pull request merged**
