### PR TITLE
feat: enable overrideMethod middleware by default

### PR DESCRIPTION
**Pull request by fengmk2**
only allow override method on POST request by default

https://github.com/eggjs/egg/pull/324

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
依赖 https://github.com/node-modules/koa-override/pull/3/files 合并发布

**Comment by fengmk2** [comment]
appveyor 只是 report 问题，test 是过的

**Comment by dead-horse** [comment]
windows 下挂了？

**Comment by dead-horse** [comment]
合并了

**Comment by fengmk2** [comment]
我提个release pr

**Comment by fengmk2** [comment]
跟 https://github.com/eggjs/egg/pull/1027 一起合并再发版本。

**Pull request merged**
