### PR TITLE
Release 2.9.0

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
更新了 https://github.com/eggjs/egg/pull/2650

**Comment by popomore** [comment]
没改 package.json

**Comment by atian25** [comment]
哈

**Comment by popomore** [comment]
https://github.com/eggjs/egg/commit/f249cbe1ad603f5f28b5b106f0e9215612cfb495

**Comment by popomore** [comment]
+ egg@2.9.0

**Pull request merged**
