### PR TITLE
docs: fix text error

### PR DESCRIPTION
**Pull request by jxDeveloper**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by jxDeveloper** [comment]
fix text error

**Comment by atian25** [comment]
thanks for PR,  `en/core/cluster-and-ipc.md` is need to fix too.

**Comment by atian25** [comment]
don't need to close, just push another commit in the same branch and push

**Comment by jxDeveloper** [comment]
嗯嗯，谢谢提醒。我把中英文的错别字都修改了，重新提交了个PR

**Pull request closed without merging**
