### PR TITLE
docs: improve doc theme

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

doc

##### Description of change

- change menu toc
- replace .md to .html
- link anchor support
- fix broken link

```bash
$ npm run doc-server
$ open http://localhost:4000/zh-cn/
```

### CODE REVIEW

**Comment by popomore** [comment]
现在还不支持默认 lang，先访问 zh-cn

**Comment by popomore** [comment]
en-us 移到 en 了

**Comment by popomore** [comment]
```
#0 [200] request http://localhost:4000/zh-cn/
#1 [200] request http://localhost:4000/zh-cn/intro/
#2 [200] request http://localhost:4000/release/
#3 [200] request http://localhost:4000/
#4 [404] request http://localhost:4000/intro/, referer http://localhost:4000/
#5 [200] request http://localhost:4000/zh-cn/intro/index.html
#6 [200] request http://localhost:4000/zh-cn/intro/egg-and-koa.html
#7 [200] request http://localhost:4000/zh-cn/basics/extend.html
#8 [200] request http://localhost:4000/zh-cn/intro/quickstart.html
#9 [200] request http://localhost:4000/zh-cn/basics/controller.html
#10 [200] request http://localhost:4000/zh-cn/basics/router.html
#11 [200] request http://localhost:4000/zh-cn/basics/middleware.html
#12 [200] request http://localhost:4000/zh-cn/basics/config.html
#13 [200] request http://localhost:4000/zh-cn/basics/env.html
#14 [200] request http://localhost:4000/zh-cn/basics/schedule.html
#15 [200] request http://localhost:4000/zh-cn/basics/app-start.html
#16 [200] request http://localhost:4000/zh-cn/core/security.html
#17 [200] request http://localhost:4000/zh-cn/core/httpclient.html
#18 [200] request http://localhost:4000/zh-cn/core/logger.html
#19 [200] request http://localhost:4000/zh-cn/core/error-handling.html
#20 [200] request http://localhost:4000/zh-cn/core/i18n.html
#21 [200] request http://localhost:4000/zh-cn/advanced/cluster.html
#22 [200] request http://localhost:4000/zh-cn/advanced/framework.html
#23 [200] request http://localhost:4000/zh-cn/advanced/plugin.html
#24 [200] request http://localhost:4000/zh-cn/advanced/loader.html
#25 [404] request http://localhost:4000/zh-cn/basics/service.html, referer http://localhost:4000/zh-cn/advanced/loader.html
#26 [200] request http://localhost:4000/zh-cn/contributing.html
#27 [404] request http://localhost:4000/zh-cn/practice/view.html, referer http://localhost:4000/zh-cn/basics/controller.html
#28 [404] request http://localhost:4000/zh-cn/core/unittest.html, referer http://localhost:4000/zh-cn/intro/quickstart.html
```

还有一些文件没创建，会有死链

**Comment by fengmk2** [comment]
@dead-horse 的 env 修改合并了，冲突了，需要 rebase 一下

**Comment by popomore** [comment]
```
#4 [404] request http://localhost:4000/intro/, referer http://localhost:4000/
#26 [404] request http://localhost:4000/zh-cn/core/unittest.html, referer http://localhost:4000/zh-cn/basics/service.html
#28 [404] request http://localhost:4000/zh-cn/practice/view.html, referer http://localhost:4000/zh-cn/basics/controller.html
```

还有三个

**Pull request merged**
