### PR TITLE
feat: remove instrument

### LINKED ISSUE #280: 将 instrument 做成插件
现在的功能比较鸡肋，做成插件后可以持续优化而不影响框架。

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change

Closes #280

### CODE REVIEW

**Comment by fengmk2** [comment]
内部要加个 issue 记录下来

**Comment by popomore** [comment]
已经加过了

**Comment by dead-horse** [comment]
+1 合并了

**Comment by atian25** [comment]
specification 这个还要保留么?

**Pull request merged**
