### PR TITLE
fix: fix 404 page url

### PR DESCRIPTION
**Pull request by fsiaonma**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
放空的吧，不要放中文

**Comment by atian25** [comment]
那就空的吧，加一个： `This document is still waiting for translation,  see [Chinese Version](xxxx)`

**Comment by popomore** [comment]
用例还是挂的，本地先跑一下

**Comment by fsiaonma** [comment]
@atian25  ok 已经修改。

**Pull request merged**
