### PR TITLE
chore(typings): export PowerPartial

### PR DESCRIPTION
**Pull request by waitingsong**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by waitingsong** [comment]
export  PowerPartial for use of
```ts
import { EggAppConfig, PowerPartial } from 'egg'

// for config.{env}.ts
export type DefaultConfig = PowerPartial<EggAppConfig & BizConfig>
```

**Comment by atian25** [comment]
rebase。。。

**Comment by atian25** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by waitingsong** [comment]
没想到主库上面也有个 typings 分支。。。
我重新提交PR吧

**Comment by atian25** [comment]
不用的，你可以选择合并到哪个分支的

**Pull request closed without merging**
