### PR TITLE
docs(advanced/loader): translate

### PR DESCRIPTION
**Pull request by Azard**
##### Checklist

- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

`docs/source/en/advanced/loader.md`

##### Description of change

tranlation

### CODE REVIEW

**Comment by atian25** [comment]
hey, since we just update this docs for 2.x, so sorry for that, you need to checkout the newest zh_CN version and compare it.

**Comment by Azard** [comment]
👌  get it

**Comment by dead-horse** [comment]
@Azard rebase 一下，loader 的文档可能有更新，再对一下我先合并

**Comment by Azard** [comment]
@dead-horse 已经 rebase 了

**Pull request merged**
