### PR TITLE
feat: use appInfo.root in config

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change

And upgrade deps

### CODE REVIEW

**Comment by popomore** [comment]
https://github.com/eggjs/egg-core/pull/30

**Comment by atian25** [comment]
+1

**Comment by popomore** [comment]
Windows 还是那个 schedule 不稳定

**Comment by fengmk2** [comment]
+1

**Pull request merged**
