### PR TITLE
docs(logger): the unit of maxFileSize should be byte

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

Closes https://github.com/eggjs/egg/issues/2555

### CODE REVIEW

**Comment by dead-horse** [comment]
感觉把代码改成 2g 更好一点？

**Comment by dead-horse** [comment]
@popomore 怎么看

**Comment by popomore** [comment]
我改下

**Comment by popomore** [comment]
@dead-horse 好了

**Pull request merged**
