### PR TITLE
docs: fix quickstart typo

### PR DESCRIPTION
**Pull request by cycgit**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by atian25** [comment]
rebase master

**Comment by atian25** [comment]
还有对应的 https://github.com/eggjs/egg/blob/master/docs/source/en/intro/quickstart.md 也改改

**Comment by cycgit** [comment]
ok

**Comment by atian25** [comment]
再 rebase 下

**Comment by atian25** [comment]
比较简单, 先合了.

**Pull request merged**
