### PR TITLE
chore: Release the first stable version :egg: :clap::clap::clap:

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

Closes https://github.com/eggjs/egg/issues/5

### CODE REVIEW

**Comment by jtyjty99999** [comment]
:clap::clap::clap:

**Comment by fengmk2** [comment]
@popomore Please merge and release!

**Comment by popomore** [comment]
覆盖率降低和 egg-bin 有关系？

**Comment by atian25** [comment]
@popomore 换回去 2.x 跑跑看?

**Comment by popomore** [comment]
`istanbul bin is not found` 没找到，本地是可以跑过的

**Comment by atian25** [comment]
有可能是这个原因，

https://github.com/eggjs/egg-bin/blob/master/lib/cmd/cov.js#L59

上面复制了，下面才赋值，我发个 PR 修复下

**Comment by atian25** [comment]
win 又卡在了 -.-

**Comment by popomore** [comment]
覆盖率好像解决了

**Comment by popomore** [comment]
+ egg@1.0.0

**Comment by atian25** [comment]
https://zhuanlan.zhihu.com/p/25860846

**Pull request merged**
